# Omakase Ruby styling for Rails
# inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Enabled: false

Lint/FloatComparison:
  Enabled: false
Lint/LiteralAsCondition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FloatDivision:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SymbolArray:
  Enabled: false